CREATE DATABASE IF NOT EXISTS LAY_NOTE_DB;
USE LAY_NOTE_DB;

CREATE TABLE USERS (
    USER_ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()) COMMENT '유저 고유 식별자 (UUID)',
    USER_EMAIL VARCHAR(255) NOT NULL COMMENT '유저 이메일 (로그인 ID)',
    USER_PASSWORD VARCHAR(255) NOT NULL COMMENT '유저 비밀번호 (암호화 저장 권장)',
    USER_NAME VARCHAR(255) NOT NULL COMMENT '유저 이름 (실명)',
    NICK_NAME VARCHAR(255) NOT NULL COMMENT '유저 닉네임',
    USER_PHONE VARCHAR(255) NOT NULL COMMENT '전화번호',
    PROFILE_IMAGE_URL VARCHAR(255) NOT NULL COMMENT '프로필 이미지 URL'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='유저 정보 테이블';

CREATE TABLE NOTE_PROJECTS (
    NOTE_PROJECT_ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()) COMMENT '프로젝트 고유 ID',
    NOTE_PROJECT_IMAGE_URL VARCHAR(255) NOT NULL COMMENT '프로젝트 대표 이미지 URL',
    NOTE_PROJECT_TITLE VARCHAR(255) NOT NULL COMMENT '프로젝트 제목',
    NOTE_PROJECT_OWNER_ID CHAR(36) NOT NULL COMMENT '프로젝트 소유자 (USERS 참조)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    DELETED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '삭제일시 (Soft Delete 용)',
	CONSTRAINT FK_NP_OWNER FOREIGN KEY (NOTE_PROJECT_OWNER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_NP_OWNER (NOTE_PROJECT_OWNER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='노트 프로젝트 메인 테이블';

CREATE TABLE NOTE_PROJECT_PINS (
  PIN_ID           CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  USER_ID           CHAR(36) NOT NULL,
  NOTE_PROJECT_ID   CHAR(36) NOT NULL,
  CREATED_AT        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UK_USER_PROJECT (USER_ID, NOTE_PROJECT_ID),
  INDEX IDX_USER (USER_ID),
  INDEX IDX_PROJECT (NOTE_PROJECT_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
  FOREIGN KEY (NOTE_PROJECT_ID) REFERENCES NOTE_PROJECTS(NOTE_PROJECT_ID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='노트 프로젝트 핀고정 테이블';

CREATE TABLE IF NOT EXISTS NOTE_PROJECT_USERS (
    NOTE_PROJECT_ID CHAR(36) NOT NULL,
    USER_ID         CHAR(36) NOT NULL,
    USER_ROLE       ENUM('OWNER','MEMBER','GUEST') NOT NULL,
    PRIMARY KEY (NOTE_PROJECT_ID, USER_ID),
    CONSTRAINT FK_NPU_PROJECT FOREIGN KEY (NOTE_PROJECT_ID) REFERENCES NOTE_PROJECTS(NOTE_PROJECT_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NPU_USER    FOREIGN KEY (USER_ID)        REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX IDX_NPU_PROJECT_ROLE (NOTE_PROJECT_ID, USER_ROLE),
    INDEX IDX_NPU_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='프로젝트 참여하는 사용자 테이블'; 

CREATE TABLE NOTE_PROJECT_JOINS (
    PROJECT_JOIN_ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()) COMMENT '참여 신청 고유 ID',
    NOTE_PROJECT_ID CHAR(36) NOT NULL COMMENT '프로젝트 ID',
    USER_ID CHAR(36) NOT NULL COMMENT '신청한 유저 ID',
    JOIN_STATUS ENUM ('PENDING','APPROVED','REJECTED') DEFAULT 'PENDING' COMMENT '참여 신청 상태',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '신청 일시',
    DECIDED_AT DATETIME DEFAULT NULL COMMENT '승인/거절 일시',
	CONSTRAINT FK_NPJ_PROJECT FOREIGN KEY (NOTE_PROJECT_ID) REFERENCES NOTE_PROJECTS(NOTE_PROJECT_ID) ON DELETE CASCADE,
	CONSTRAINT FK_NPJ_USER    FOREIGN KEY (USER_ID)        REFERENCES USERS(USER_ID) ON DELETE CASCADE,
	INDEX IDX_NPJ_PROJECT_STATUS (NOTE_PROJECT_ID, JOIN_STATUS),
	INDEX IDX_NPJ_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='프로젝트 참여 신청 테이블';

CREATE TABLE NOTE_PROJECT_COMPOSITIONS (
    NOTE_COMPOSITION_ID CHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY COMMENT '노트 구성요소 고유 ID',
    NOTE_PROJECT_ID CHAR(36) NOT NULL COMMENT '소속 프로젝트 ID',
    NOTE_BOX_ID BIGINT  COMMENT '노트 박스 고유 ID',
    NOTE_IMAGE_BOX_LIST_ID BIGINT  COMMENT '이미지 박스 리스트 고유 ID',
    NOTE_LIST_ID BIGINT  COMMENT '노트 리스트 고유 ID',
    NOTE_COMPONENT_TYPE ENUM('NOTEBOX', 'NOTELIST', 'NOTEIMAGEBOX') NOT NULL COMMENT '요소 타입',
    COMPOSITION_X INT NOT NULL COMMENT 'X 좌표',
    COMPOSITION_Y INT NOT NULL COMMENT 'Y 좌표',
    COMPOSITION_Z INT NOT NULL COMMENT 'Z 인덱스(앞뒤)',
    COMPOSITION_Z2 INT NOT NULL COMMENT '보조 Z 인덱스',
    FOREIGN KEY (NOTE_PROJECT_ID) REFERENCES NOTE_PROJECTS(NOTE_PROJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (NOTE_BOX_ID) REFERENCES NOTE_BOXES(NOTE_BOX_ID) ON DELETE CASCADE,
    FOREIGN KEY (NOTE_IMAGE_BOX_LIST_ID) REFERENCES NOTE_IMAGE_BOX_LIST(NOTE_IMAGE_BOX_LIST_ID) ON DELETE CASCADE,
    FOREIGN KEY (NOTE_LIST_ID) REFERENCES NOTE_LIST(NOTE_LIST_ID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='노트 구성요소 배치 테이블';

CREATE TABLE NOTE_BOXES (
    NOTE_BOX_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '노트 박스 고유 ID',
    NOTE_BOX_TITLE VARCHAR(255) COMMENT '노트 박스 제목',
    NOTE_BOX_CONTENT VARCHAR(255) COMMENT '노트 박스 내용',
    IMAGE_URL VARCHAR(255) COMMENT '첨부 이미지 URL'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='텍스트 박스 요소 테이블';

CREATE TABLE NOTE_IMAGE_BOXES (
    NOTE_IMAGE_BOX_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '이미지 박스 고유 ID',
    NOTE_IMAGE_BOX_LIST_ID BIGINT COMMENT '이미지 박스 리스트 고유 ID',
    IMAGE_CAPTION VARCHAR(255)  COMMENT '이미지 설명',
    IMAGE_URL VARCHAR(255) COMMENT '이미지 URL',
    FOREIGN KEY (NOTE_IMAGE_BOX_LIST_ID) REFERENCES NOTE_IMAGE_BOX_LIST(NOTE_IMAGE_BOX_LIST_ID) ON DELETE CASCADE 
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='이미지 박스 요소 테이블';

CREATE TABLE NOTE_IMAGE_BOX_LIST (
    NOTE_IMAGE_BOX_LIST_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '이미지 박스 리스트 고유 ID'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='이미지 박스 요소 테이블';

CREATE TABLE NOTE_LIST (
    NOTE_LIST_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '노트 리스트 고유 ID',
    NOTE_LIST_TITLE VARCHAR(255) COMMENT '노트 리스트 제목'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='체크리스트 요소 테이블';

CREATE TABLE NOTE_LIST_ITEMS (
    NOTE_LIST_ITEM_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '리스트 아이템 고유 ID',
    NOTE_LIST_ID BIGINT NOT NULL COMMENT '소속 노트 리스트 ID',
    NOTE_LIST_CONTENT VARCHAR(255)  COMMENT '리스트 항목 내용',
    NOTE_LIST_CHECK BOOLEAN DEFAULT FALSE COMMENT '체크 여부',
    FOREIGN KEY (NOTE_LIST_ID) REFERENCES NOTE_LIST(NOTE_LIST_ID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='노트 리스트의 아이템 테이블';


